# Generated by Django 3.2 on 2021-05-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
