# Generated by Django 3.2 on 2021-05-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_auto_20210513_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='criteria',
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
    ]
