# Generated by Django 3.2 on 2021-05-13 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_auto_20210513_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('title', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='evaluations.criteriatype')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='criteria',
            field=models.ManyToManyField(to='evaluations.Criteria'),
        ),
    ]
