# Generated by Django 3.2 on 2021-05-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='poste',
            field=models.CharField(choices=[('S', 'Salarie'), ('RI', 'Responsable Informatique'), ('RF', 'Responsable Financier'), ('RH', 'Responsable ressources Humaines')], default='RI', max_length=2),
        ),
    ]
