# Generated by Django 3.2 on 2021-04-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='poste',
            field=models.CharField(choices=[('S', 'Salarie'), ('RI', 'Responsable Informatique'), ('CH', 'Chef Hierarchique'), ('RF', 'Responsable Financier'), ('RH', 'Responsable ressources Humaines')], default='S', max_length=2),
        ),
    ]
