# Generated by Django 3.2 on 2021-05-02 16:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adresse',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='cin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='code_postal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_naissance',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 2)),
        ),
        migrations.AddField(
            model_name='employee',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationnalite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
