# Generated by Django 3.2 on 2021-05-02 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_naissance',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
