# Generated by Django 3.2 on 2021-05-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_employee_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
