# Generated by Django 3.2 on 2021-05-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='chef',
        ),
        migrations.AlterField(
            model_name='employee',
            name='poste',
            field=models.CharField(choices=[('S', 'Salarie'), ('RI', 'Responsable Informatique'), ('RF', 'Responsable Financier'), ('RH', 'Responsable ressources Humaines')], default='S', max_length=2),
        ),
    ]
