# Generated by Django 3.2 on 2021-05-13 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210513_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='adresse',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cin',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code_postal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_naissance',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lieu_naissance',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationnalite',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
