# Generated by Django 3.2 on 2021-05-13 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('jour', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('formateur', models.CharField(max_length=200)),
                ('duree', models.IntegerField(default=1)),
                ('lieu', models.CharField(max_length=200)),
                ('sujet', models.CharField(max_length=300)),
            ],
        ),
    ]
