# Generated by Django 3.2 on 2021-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='formateur',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formation',
            name='genre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formation',
            name='lieu',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formation',
            name='sujet',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='formation',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
