# Generated by Django 3.2 on 2021-05-13 05:30

import conges.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=conges.models.one_day_hence)),
                ('conge_type', models.CharField(choices=[('A', 'annuel'), ('E', 'exceptionnel'), ('M', 'maladie'), ('R', 'recuperation')], default='A', max_length=1)),
                ('status', models.CharField(choices=[('P', 'En attente'), ('A', 'Accepté'), ('R', 'Refusé')], default='P', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CongeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.IntegerField(default=30)),
                ('conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conges.conge')),
            ],
        ),
    ]
