# Generated by Django 3.2 on 2021-05-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='status',
            field=models.CharField(choices=[('P', 'En attente'), ('A', 'Accepté'), ('R', 'Refusé')], default='P', max_length=2),
        ),
    ]
